### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by nwa2018** [lc60005457/parcel-plugin-eslint#13]
"babel-eslint": "^8.2.5",
    "eslint": "^5.0.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "parcel-plugin-eslint": "^1.0.4"

this is my package.json，when I run parcel ./index.js，I'am blocked by the below error

/Users/fujuewen/private/github/myLodash/index.js: Cannot read property 'length' of null
    at /Users/fujuewen/private/github/myLodash/node_modules/parcel-plugin-eslint/node_modules/eslint-friendly-formatter/index.js:184:74
    at Array.reduce (<anonymous>)
    at module.exports (/Users/fujuewen/private/github/myLodash/node_modules/parcel-plugin-eslint/node_modules/eslint-friendly-formatter/index.js:160:17)
    at MyAsset.load (/Users/fujuewen/private/github/myLodash/node_modules/parcel-plugin-eslint/src/EslintAsset.js:22:23)
    at <anonymous>

**Comment by alexstep** [comment]
@nwa2018  

1. add to your eslintrc 'parser'  : 'babel-eslint' 
example my file .eslintrc.js
```
module.exports = {
  'extends' : 'standard',
  'parser'  : 'babel-eslint'
};
```
2. check thant your .babelrc have valid json syntax.


This steps fix my some problem
